#!/usr/bin/env python3
"""
Generate a markdown report from the JSON translation scan report.

This script reads the JSON report generated by scan_missing_translations.py
and creates a concise markdown summary suitable for inclusion in README.md.
"""

import json
import argparse
import sys
from pathlib import Path
from datetime import datetime


def load_json_report(json_path: str) -> dict:
    """Load JSON report from file."""
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: Report file not found: {json_path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Failed to parse JSON report: {e}", file=sys.stderr)
        sys.exit(1)


def format_date(date_str: str) -> str:
    """Format ISO date string to readable format."""
    try:
        dt = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
        return dt.strftime('%Y-%m-%d %H:%M:%S UTC')
    except Exception:
        return date_str


def generate_markdown_report(report: dict) -> str:
    """Generate markdown report from JSON report data."""
    summary = report.get('summary', {})
    posts = report.get('posts', [])
    
    total_posts = summary.get('total_posts_scanned', 0)
    posts_with_missing = summary.get('posts_with_missing_translations', 0)
    posts_complete = summary.get('posts_complete', 0)
    all_complete = summary.get('all_complete', False)
    expected_langs = summary.get('expected_languages', [])
    total_expected = summary.get('total_expected_languages', 0)
    date_generated = summary.get('date_generated', '')
    
    lines = []
    
    # Header with status indicator
    if all_complete:
        lines.append("✅ **All blog posts have complete translations!**")
    else:
        lines.append(f"⚠️ **{posts_with_missing} post(s) missing translations**")
    
    lines.append("")
    
    # Summary statistics
    lines.append("### Summary")
    lines.append("")
    lines.append(f"- **Total posts scanned**: {total_posts}")
    lines.append(f"- **Posts with complete translations**: {posts_complete}")
    lines.append(f"- **Posts missing translations**: {posts_with_missing}")
    lines.append(f"- **Expected languages**: {total_expected}")
    
    if date_generated:
        lines.append(f"- **Last updated**: {format_date(date_generated)}")
    
    lines.append("")
    
    # All posts with missing translations
    if posts_with_missing > 0:
        lines.append("### Posts Needing Attention")
        lines.append("")
        # Sort by missing_count descending, then by post path
        sorted_posts = sorted(posts, key=lambda x: (x.get('missing_count', 0), x.get('path', '')), reverse=True)
        
        for post in sorted_posts:
            post_path = post.get('path', '')
            missing_count = post.get('missing_count', 0)
            total_expected = post.get('total_expected', 0)
            url = post.get('url', '')
            
            # Extract post name from path for display
            post_name = post_path.split('/')[-1] if '/' in post_path else post_path
            
            if url:
                lines.append(f"- [{post_name}]({url}) - {missing_count}/{total_expected} translations missing")
            else:
                lines.append(f"- {post_name} - {missing_count}/{total_expected} translations missing")
        
        lines.append("")
    
    return "\n".join(lines)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Generate markdown report from JSON translation scan report',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        '--input',
        type=str,
        required=True,
        help='Path to input JSON report file'
    )
    
    parser.add_argument(
        '--output',
        type=str,
        required=True,
        help='Path to output markdown file'
    )
    
    args = parser.parse_args()
    
    # Load JSON report
    report = load_json_report(args.input)
    
    # Generate markdown
    markdown_content = generate_markdown_report(report)
    
    # Write to output file
    try:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        print(f"Markdown report saved to: {args.output}", file=sys.stderr)
    except Exception as e:
        print(f"Error writing markdown report: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
