name: Deploy to blog-qa.groupdocs.com

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GroupDocs Blog repo
        uses: actions/checkout@main
        with:
          repository: groupdocs/groupdocs-blog
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: hugo --config "config.yml,config.staging.yml" --buildDrafts --cleanDestinationDir #--minify #-b "https://blog-qa.groupdocs.com/"  
    
      - name: Deploy Home to S3 - (Staging)
        run: hugo deploy --maxDeletes -1 --config "config.yml,config.staging.yml" --buildDrafts --target "staging"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
          PATHS: '/*'
          AWS_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
