name: Production

on:
  push:
    branches:
      - main  # Set a branch to deploy
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GroupDocs Blog repo
        uses: actions/checkout@4
        with:
          repository: groupdocs/groupdocs-blog
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        # run: hugo --config "config.yml" #--minify
        run: hugo --config "config.yml,config.production.yml" --minify
    
      - name: Deploy Home to S3
        # run: hugo deploy --maxDeletes -1 --target "production"
        run: hugo deploy --maxDeletes -1 --config "config.yml,config.production.yml" --target "production"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
